services:
  postgres:
    image: postgres:15-alpine
    container_name: recipe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: recipeuser
      POSTGRES_PASSWORD: recipepassword
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_PATH: postgres://recipeuser:recipepassword@postgres:5432/recipes?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 8000
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    networks:
      - recipe-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recipe-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - recipe-network

volumes:
  postgres_data:
    driver: local

networks:
  recipe-network:
    driver: bridge
